add_feature_before_output: true
alt_exonic_seq_length: 40
alt_intronic_seq_length: 40
batch_norm_decay: 0.9
batch_normalization: true
batch_sizes: [25, 10, 5, 1, 1]
buckets: [0, 20, 50, 100, 500]
comm_NN_LSTM: false
comm_NN_LSTM_alternate: true
comm_NN_LSTM_layers: 2
comm_NN_LSTM_size: 100
comm_NN_LSTM_steps: 5
comm_NN_conv: true
comm_NN_fc: false
comm_NN_fc_final: true
const_exonic_seq_length: 40
const_intronic_seq_length: 40
conv_params:
- [24, 8, 1, 1, 1]
- [5, 12, 1, 1, 1]
- [3, 24, 1, 1, 1]
- [1, 1, 1, 1, 1]
data_dir: /path/to/dataset/donor
dataset_type: dynamic
dropout_keep_prob: 0.8
early_stopping_delay: 6
event_type: donor
features: [intron_length]
graphing_frequency: 1000
hidden_units: [300, 150, 120]
init_scale_LSTM: 0.1
init_scale_conv: 0.01
init_scale_fc: 0.01
init_scale_fc_final: 0.0001
l2_decay: 0.01
learning_rate: 0.001
lr_decay: true
lr_decay_rate: 0.5
lr_decay_step: [100000, 150000, 200000]
make_rundir: false
max_grad_norm: 20
max_sgd_steps: 600005
n_validation_files: 5
n_validation_steps: 2000
num_epochs: 1000
num_outputs: 1
out_LSTM_size: 100
output_LSTM: false
output_LSTM_bidirectional: true
residual_alt_dna: false
train_dir: /path/to/train/dir/donor/comm_network/
validation_frequency: 5000
